name: Build and Push DiaNN Docker Images

on:
  push:
    branches: [ "main" ]
    paths:
      - 'diann-*/Dockerfile'
      - '.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'diann-*/Dockerfile'
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      push_images:
        description: 'Push images to registry'
        required: false
        default: true
        type: 'boolean'

jobs:
  build:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      RETRY_TIMES: 3
      RETRY_DELAY: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Extract metadata for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/bigbio/diann
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value={{date 'YYYY.MM.DD'}}

    - name: Set date tag
      id: date
      run: echo "DATE_TAG=$(date +'%Y.%m.%d')" >> $GITHUB_OUTPUT

    - name: Build and Push DiaNN 2.1.0 image (Latest)
      uses: docker/build-push-action@v5
      with:
        context: ./diann-2.1.0
        push: ${{ (github.event.inputs.push_images == true || github.event.inputs.push_images == '') }}
        tags: |
          ghcr.io/bigbio/diann:2.1.0
          ghcr.io/bigbio/diann:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        provenance: false

    - name: Set up Singularity
      if: ${{ (github.event.inputs.push_images == true || github.event.inputs.push_images == '') }}
      uses: eWaterCycle/setup-singularity@v7
      with:
        singularity-version: 3.8.7

    - name: Pull Docker image for Singularity conversion
      if: ${{ (github.event.inputs.push_images == true || github.event.inputs.push_images == '') }}
      run: |
        # Pull the Docker image from GitHub Container Registry
        docker pull ghcr.io/bigbio/diann:2.1.0
        # Save the Docker image to a tar file
        docker save ghcr.io/bigbio/diann:2.1.0 -o diann-2.1.0.tar

    - name: Convert Docker image to Singularity
      if: ${{ (github.event.inputs.push_images == true || github.event.inputs.push_images == '') }}
      run: |
        # Convert Docker tar to Singularity SIF
        singularity build diann-2.1.0.sif docker-archive://diann-2.1.0.tar
        # Verify the SIF file exists
        ls -la diann-2.1.0.sif

    - name: Login and Deploy Container
      if: (github.event_name != 'pull_request')
      env:
        keepgoing: ${{ env.keepgoing }}
      run: |
        if [[ "${keepgoing}" == "true" ]]; then
          echo ${{ secrets.GHCR_TOKEN }} | singularity remote login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
          singularity push diann-2.1.0.sif oras://bigbio/diann-sif:2.1.0
          singularity push diann-2.1.0.sif oras://bigbio/diann-sif:latest
        fi

    - name: Notify on success
      if: success()
      run: |
        echo "::notice::Successfully built and pushed DiaNN Docker and Singularity images to ghcr.io/bigbio"

    - name: Notify on failure
      if: failure()
      run: |
        echo "::error::Failed to build or push DiaNN images. Check the logs for details."